name: My Yoga Journal
favicon: null
layout_spectrum: 0.30748626915737987
typography_spectrum: 0.995366545394063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.44933530408889055
  lightness: 0.6137158842757344
  saturation: 0.287802891805768
  rhythmicContrast: 0.13108911830931902
purpose: []
