name: My Yoga Journal 黒猫のヨガ日記
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47989
title: 'Morning Yoga, sometimes with a black cat'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76197069-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0
  lightness: 0.6137158842757344
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
